language: ruby
rvm:
- 2.3.1
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database blog2_test;' -U postgres
script:
- bundle exec rake db:migrate
- bundle exec rake
notifications:
  slack: nird:BqbUGQOgg2pFAVDIX0FZVh4l
