---
applications:
- name: adam_blog
  domain: run.platform.nirdhost.com
  domain: adamdbell.com
  hosts: [ www ]
  services:
    - adam_blog_production
  command: bundle exec rake cf:on_first_instance db:migrate && bundle exec rails s -p $PORT -e $RAILS_ENV
  memory: 512M
  instances: 1
