default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: blog2_development

test:
  <<: *default
  database: blog2_test

production:
  <<: *default
  database: blog2_prod
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
