default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>


development:
  <<: *default
  database: blog_dev
  port: 5432

test:
  <<: *default
  database: blog2_test

production:
  <<: *default
  adapter: postgresql
